hosted_storage_type: nfs
storage_domain_type: "{{ 'nfs3' if hosted_storage_type == 'nfs' else hosted_storage_type }}"
cpu_model: model_Nehalem
gateway: '{{ ansible_default_ipv4.gateway}}'
interface_name: '{{ ansible_default_ipv4.interface }}'
hosted_storage_name: my_hosted_storage
hosted_storage_address: www.example.com
config_dir: /etc/ansible-ovirt
hosted_storage_path: /path/to/storage
admin_password: changeme
host_id: 2
host_name: hosted_engine_{{ host_id }}
