---

- name: Install dependences
  yum: name={{item}} state=present
  with_items:
    - ovirt-hosted-engine-setup
    - glusterfs-fuse
    - glusterfs-cli
  async: 3600
  poll: 5
  tags:
    - packages

- name: create config directory
  file:
      path: '{{ config_dir }}'
      state: directory
      mode: 0600
  tags:
    - setup

- name: Get the answer file over there
  template:
      src: answers.j2
      dest: '{{ config_dir }}/answers'
      mode: 0600
  tags:
    - setup

- name: Execute hosted-engine setup
  shell: hosted-engine --deploy --config-append={{ config_dir }}/answers
  async: 12000
  poll: 5
  tags:
    - install

- name: Restart imageio-daemon
  service:
    name: ovirt-imageio-daemon
    state: restarted
